### ISSUE TITLE
Flatpak 1.9.1 Not working on Steam Deck

### ISSUE THREAD

**Issue by guymanley** [Matoking/protontricks#164]
**Describe the bug**
Protontricks seems to crash or hang after selecting a game in the initial menu. No subsequent windows show up. Tried from konsole/terminal "flatpak run com.github.Matoking.protontricks --gui". Select a game. No new window shows up. Tried with -v --no-bwrap flags. See Additional Content section for output. Once you select a game from there it goes a little further but then displays an error window stating "bug: w_metadata art2kmin has a unix path for installed_file1, should be a windows path". It does this for any game, ones that I know are windows games.

**To Reproduce**
Gui
1. Launched Protontricks from the app/start menu.
2. Select a game, click ok.
3. Nothing happens, no new window drawn.
Terminal/troubleshooting
1. Run command `flatpak run com.github.Matoking.protontricks -v --no-bwrap --gui`
4. Command fails and error is displayed: bug: w_metadata art2kmin has a unix path for installed_file1, should be a windows path

**Expected behavior**
Run protontricks from gui. Select game, have the action menu show up to edit prefix, registry etc.

**System (please complete the following information):**
 - Distro: SteamOS 3.3.1 (stable branch)
 - Protontricks installation method: Flatpak
 - Protontricks version: 1.9.1
 - Steam version: Stable Branch

**Additional context**

(deck@deckmanley ~)$ flatpak run com.github.Matoking.protontricks -v --no-bwrap --gui
protontricks (INFO): Running inside Flatpak sandbox, version 1.12.4.
protontricks (INFO): Found Steam directory at /home/deck/.local/share/Steam
protontricks (INFO): Using Steam directory at /home/deck/.local/share/Steam. You can also define Steam directory manually using $STEAM_DIR
protontricks (INFO): Using default Steam Runtime at /home/deck/.local/share/Steam/ubuntu12_32/steam-runtime
protontricks (INFO): WINETRICKS environment variable is not available. Searching from $PATH.
protontricks (INFO): Found 2 Steam library folders
protontricks (WARNING): Unknown Flatpak file system permission 'xdg-pictures', ignoring.
protontricks (WARNING): Unknown Flatpak file system permission 'xdg-music', ignoring.
protontricks (WARNING): Unknown Flatpak file system permission 'xdg-videos', ignoring.
protontricks (WARNING): Unknown Flatpak file system permission 'xdg-download', ignoring.
protontricks (WARNING): Unknown Flatpak file system permission 'xdg-documents', ignoring.
protontricks (WARNING): Unknown Flatpak file system permission 'xdg-desktop', ignoring.
protontricks (INFO): Multiple compatdata directories found for app 1730680
protontricks (INFO): Multiple compatdata directories found for app 310360
protontricks (INFO): Multiple compatdata directories found for app 253750
protontricks (INFO): Multiple compatdata directories found for app 464060
protontricks (INFO): Multiple compatdata directories found for app 940910
protontricks (INFO): Multiple compatdata directories found for app 692850
protontricks (INFO): Multiple compatdata directories found for app 254700
protontricks (INFO): Multiple compatdata directories found for app 1306630
protontricks (INFO): Multiple compatdata directories found for app 360830
protontricks (INFO): Multiple compatdata directories found for app 360740
protontricks (INFO): Currently logged-in Steam user: kutabachimaeyo
protontricks (INFO): Found 5 Steam shortcuts running using Steam compatibility tools
protontricks (INFO): Using 'yad' as GUI provider
protontricks (INFO): The current device is a Steam Deck
protontricks (INFO): We're on a Steam Deck, checking if compatibility profile is available for the app
protontricks (INFO): App has Steam Deck compatibility profile with Proton version: proton-stable
protontricks (INFO): Found active compatibility tool: Proton 7.0
protontricks (INFO): Active compatibility tool is a Proton installation
protontricks (INFO): Using separately installed Steam Runtime: Steam Linux Runtime - Soldier
protontricks (INFO): Created Steam Runtime Wine binary directory at /home/deck/.var/app/com.github.Matoking.protontricks/cache/protontricks/proton/Proton 7.0/bin
protontricks (INFO): WINE environment variable is not available. Setting WINE environment variable to Proton bundled version.
protontricks (INFO): WINESERVER environment variable is not available. Setting WINESERVER environment variable to Proton bundled version
protontricks (INFO): Attempting to run command ['/app/bin/winetricks', '--gui']
Gtk-Message: 22:14:22.224: Failed to load module "canberra-gtk-module"
winetricks GUI enabled, using zenity 3.32.0
Executing mkdir -p /home/deck/.local/share/Steam/steamapps/compatdata/254700
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Gtk-Message: 22:14:33.407: Failed to load module "canberra-gtk-module"
Using winetricks 20220411 - sha256sum: 69856050cfe9d97902dfd68c1ad42a10a4be0fe76660744126d7e3ed75610495 with wine-7.0 and WINEARCH=win64
Gtk-Message: 22:14:39.994: Failed to load module "canberra-gtk-module"

Here's where the "w_metadata art2kmin has a unix path for installed_file1, should be a windows path" error window is drawn.

**Comment by chrisgix** [comment]
I am also on 1.9.1 and having the same issue on steam deck

**Comment by Matoking** [comment]
I think I have narrowed this down to a race condition in a Wine launcher script, causing new Wine processes to crash when the previous Wine process finishes shutting down during a very inopportune gap of time. Though this could happen in pretty much environment, it seems to happen pretty much always when Flatpak version of Protontricks is used and bwrap is disabled. Chances are the fix may solve other random issues and crashes as well.

I've pushed a fix for testing [here](https://github.com/flathub/com.github.Matoking.protontricks/pull/29), which you can install by running the following command:

```
flatpak install --user https://dl.flathub.org/build-repo/104592/com.github.Matoking.protontricks.flatpakref
```

Since you're on Steam Deck, you should be able to launch Konsole and paste that command to install the fix.

Can you test running Protontricks **both** with bwrap on and off after installing the fix, and check if that solves the issue?

**Comment by witcheslive** [comment]
I am running into this exact issue as well, and unfortunately this does not seem to fix it. I don't know what bwrap is or how to turn it on or off though.

**Comment by witcheslive** [comment]
Sorry, update, after posting I realized bwrap is an option on the command line. I used the bash command the op wrote with the no-bwrap option instead of the desktop UI (which I assume has it on?) and it did load, though it seemed to go to generic winetricks and not the specific one for the game I selected

**Comment by Matoking** [comment]
@witcheslive Did you try installing the fix using the command in the previous command, and did it install successfully? If so, can you post the output with `--no-bwrap` and without it? In short, you'll want to test both of these on the command-line:

```
flatpak run com.github.Matoking.protontricks -v --gui
```

and

```
flatpak run com.github.Matoking.protontricks -v --no-bwrap --gui
```

Both should ideally work, and the first one **without** `--no-bwrap` especially should work. In short, bwrap should more closely match how Steam runs the game, and it should work by default in almost all cases. 

You can upload the output to [gist.github.com](https://gist.github.com/) and then copy the link here.

**Comment by witcheslive** [comment]
unfortunately due to circumstances, can't get a keyboard plugged in and couldn't get a copy and paste, so going to have to boomershot. this is the output for running the command in the window title, it did not bring up anything after selecting the game

![protontrickshelp](https://user-images.githubusercontent.com/42488274/187272640-c61fe727-85f0-4098-973c-49e316b6cc7b.png)

**Comment by nabel0** [comment]
Having the same probem on the steamdeck.
Running it with the command "flatpak run com.github.Matoking.protontricks -v --gui" gives this output and just hangs there after selecting a title:

(deck@steamdeck ~)$ flatpak run com.github.Matoking.protontricks -v --gui
protontricks (INFO): Running inside Flatpak sandbox, version 1.12.4.
protontricks (INFO): Found Steam directory at /home/deck/.local/share/Steam
protontricks (INFO): Using Steam directory at /home/deck/.local/share/Steam. You can also define Steam directory manually using $STEAM_DIR
protontricks (INFO): Using default Steam Runtime at /home/deck/.local/share/Steam/ubuntu12_32/steam-runtime
protontricks (INFO): WINETRICKS environment variable is not available. Searching from $PATH.
protontricks (INFO): Found 2 Steam library folders
protontricks (INFO): Currently logged-in Steam user: censored
protontricks (INFO): Found 1 Steam shortcuts running using Steam compatibility tools
protontricks (INFO): Using 'yad' as GUI provider
protontricks (INFO): The current device is a Steam Deck
protontricks (INFO): We're on a Steam Deck, checking if compatibility profile is available for the app
protontricks (INFO): App has Steam Deck compatibility profile with Proton version: proton-stable
protontricks (INFO): Found active compatibility tool: Proton 7.0
protontricks (INFO): Active compatibility tool is a Proton installation
protontricks (INFO): Using 'bwrap = True' as default value
protontricks (INFO): Using 'background-wineserver = True' as default value
protontricks (INFO): Using separately installed Steam Runtime: Steam Linux Runtime - Soldier
protontricks (INFO): Running Steam Runtime using bwrap containerization.
If any problems arise, please try running the command again using the `--no-bwrap` flag and make an issue report if the problem only occurs when bwrap is in use.
protontricks (INFO): Created Steam Runtime Wine binary directory at /home/deck/.var/app/com.github.Matoking.protontricks/cache/protontricks/proton/Proton 7.0/bin
protontricks (INFO): WINE environment variable is not available. Setting WINE environment variable to Proton bundled version.
protontricks (INFO): WINESERVER environment variable is not available. Setting WINESERVER environment variable to Proton bundled version
protontricks (INFO): Starting bwrap launcher process: /home/deck/.var/app/com.github.Matoking.protontricks/cache/protontricks/proton/Proton 7.0/bin/bwrap-launcher
protontricks (INFO): Starting wineserver keepalive process: /home/deck/.var/app/com.github.Matoking.protontricks/cache/protontricks/proton/Proton 7.0/bin/wineserver-keepalive
protontricks (INFO): Attempting to run command ['/app/bin/winetricks', '--gui']
protontricks - bwrap-launcher 13: Following directories will be mounted inside container: /app /efi /esp /etc /home /mnt /opt /sbin /srv /tmp /run/media
protontricks - bwrap-launcher 13: Using temporary directory: /tmp/protontricks-lrb9u3m8
protontricks - wineserver-keepalive 14: Starting wineserver-keepalive process...
Gtk-Message: 20:58:27.070: Failed to load module "canberra-gtk-module"
winetricks GUI enabled, using zenity 3.32.0

**Comment by nabel0** [comment]
Running it with the command "flatpak run com.github.Matoking.protontricks -v --no-bwrap --gui" gives this and it's working after selecting a title:

(deck@steamdeck ~)$ flatpak run com.github.Matoking.protontricks -v --no-bwrap --gui
protontricks (INFO): Running inside Flatpak sandbox, version 1.12.4.
protontricks (INFO): Found Steam directory at /home/deck/.local/share/Steam
protontricks (INFO): Using Steam directory at /home/deck/.local/share/Steam. You can also define Steam directory manually using $STEAM_DIR
protontricks (INFO): Using default Steam Runtime at /home/deck/.local/share/Steam/ubuntu12_32/steam-runtime
protontricks (INFO): WINETRICKS environment variable is not available. Searching from $PATH.
protontricks (INFO): Found 2 Steam library folders
protontricks (INFO): Currently logged-in Steam user: censored
protontricks (INFO): Found 1 Steam shortcuts running using Steam compatibility tools
protontricks (INFO): Using 'yad' as GUI provider
protontricks (INFO): The current device is a Steam Deck
protontricks (INFO): We're on a Steam Deck, checking if compatibility profile is available for the app
protontricks (INFO): App has Steam Deck compatibility profile with Proton version: proton-stable
protontricks (INFO): Found active compatibility tool: Proton 7.0
protontricks (INFO): Active compatibility tool is a Proton installation
protontricks (INFO): Using separately installed Steam Runtime: Steam Linux Runtime - Soldier
protontricks (INFO): Created Steam Runtime Wine binary directory at /home/deck/.var/app/com.github.Matoking.protontricks/cache/protontricks/proton/Proton 7.0/bin
protontricks (INFO): WINE environment variable is not available. Setting WINE environment variable to Proton bundled version.
protontricks (INFO): WINESERVER environment variable is not available. Setting WINESERVER environment variable to Proton bundled version
protontricks (INFO): Attempting to run command ['/app/bin/winetricks', '--gui']
Gtk-Message: 21:02:53.738: Failed to load module "canberra-gtk-module"
winetricks GUI enabled, using zenity 3.32.0
Executing mkdir -p /home/deck/.local/share/Steam/steamapps/compatdata/361420
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Gtk-Message: 21:02:54.937: Failed to load module "canberra-gtk-module"
Using winetricks 20220411 - sha256sum: 69856050cfe9d97902dfd68c1ad42a10a4be0fe76660744126d7e3ed75610495 with wine-7.0 and WINEARCH=win64
Gtk-Message: 21:03:00.007: Failed to load module "canberra-gtk-module"

**Comment by guymanley** [comment]
Sorry, Just got a chance to try this.

with bwrap https://gist.github.com/guymanley/512e29b4ca5606e9475e42246ddfd7a5

no bwrap https://gist.github.com/guymanley/52188922b0ee3b0e8430b5fbc189f8ba

I was able to enter a game's menu, click around with its file explorer, presumably everything else should work too.

**Comment by nabel0** [comment]
> Sorry, Just got a chance to try this.
> 
> with bwrap https://gist.github.com/guymanley/512e29b4ca5606e9475e42246ddfd7a5
> 
> no bwrap https://gist.github.com/guymanley/52188922b0ee3b0e8430b5fbc189f8ba
> 
> I was able to enter a game's menu, click around with its file explorer, presumably everything else should work too.

It works for you with both options?

**Comment by guymanley** [comment]
I titled the gist pages, fails with bwrap, works with no-bwrap.

**Comment by nabel0** [comment]
> I titled the gist pages, fails with bwrap, works with no-bwrap.

So it is exactly the same with you as it is with me

**Comment by Matoking** [comment]
> Sorry, Just got a chance to try this.
> 
> with bwrap https://gist.github.com/guymanley/512e29b4ca5606e9475e42246ddfd7a5
> 
> no bwrap https://gist.github.com/guymanley/52188922b0ee3b0e8430b5fbc189f8ba
> 
> I was able to enter a game's menu, click around with its file explorer, presumably everything else should work too.

Thanks for the logs! It looks like the bwrap launcher is getting stuck for some reason. Can you or anyone else in this thread try running the following command and see what output it produces:

```
flatpak run com.github.Matoking.protontricks -v -c "bash -x wine --version" APPID
```

Replace the `APPID` with the app ID for the game that's causing issues. It's the number at the end of each title when Protontricks asks you to choose a game from a list (eg. 753640 in "Outer Wilds: 753640" is the app ID).

I'm guessing the command will get stuck somehow and either produce endless amounts of log lines, or just hang entirely. Knowing where it does so should hopefully nail down the issue.

**Comment by nabel0** [comment]
> > Sorry, Just got a chance to try this.
> > with bwrap https://gist.github.com/guymanley/512e29b4ca5606e9475e42246ddfd7a5
> > no bwrap https://gist.github.com/guymanley/52188922b0ee3b0e8430b5fbc189f8ba
> > I was able to enter a game's menu, click around with its file explorer, presumably everything else should work too.
> 
> Thanks for the logs! It looks like the bwrap launcher is getting stuck for some reason. Can you or anyone else in this thread try running the following command and see what output it produces:
> 
> ```
> flatpak run com.github.Matoking.protontricks -v -c "bash -x wine --version" APPID
> ```
> 
> Replace the `APPID` with the app ID for the game that's causing issues. It's the number at the end of each title when Protontricks asks you to choose a game from a list (eg. 753640 in "Outer Wilds: 753640" is the app ID).
> 
> I'm guessing the command will get stuck somehow and either produce endless amounts of log lines, or just hang entirely. Knowing where it does so should hopefully nail down the issue.

Here you go:

https://gist.github.com/nabel0/5803f24be891d97dc33b87d046103354

**Comment by nabel0** [comment]
This was with the offical flatpak repo version..Not with the test version you send.

**Comment by Matoking** [comment]
Please install the test version, as the crash bug can make it harder to pin down the cause due to its random nature.

If it still causes the same result (the command prints the version at the last line, as it should), that would be weird. If that doesn't work, another command to run is:

```
flatpak run com.github.Matoking.protontricks -v -c "winetricks -v --gui" APPID
```

This should work pretty much the same way as the `flatpak run com.github.Matoking.protontricks -v --gui` command used earlier, except it prints a lot more information. This should pin down where the process crashes or hangs if it's related to whatever Winetricks does, which is what Protontricks uses.

**Comment by nabel0** [comment]
> Please install the test version, as the crash bug can make it harder to pin down the cause due to its random nature.
> 
> If it still causes the same result (the command prints the version at the last line, as it should), that would be weird. If that doesn't work, another command to run is:
> 
> ```
> flatpak run com.github.Matoking.protontricks -v -c "winetricks -v --gui" APPID
> ```
> 
> This should work pretty much the same way as the `flatpak run com.github.Matoking.protontricks -v --gui` command used earlier, except it prints a lot more information. This should pin down where the process crashes or hangs if it's related to whatever Winetricks does, which is what Protontricks uses.

Okay...Here ist the same command with your test version:

https://gist.github.com/nabel0/0789ea9d4386c920c8c4df6e561b0cb2

And the other command is here:

https://gist.github.com/nabel0/0e9e581e9f0cd6cd1947d14c61bd30cf

**Comment by guymanley** [comment]
> > Sorry, Just got a chance to try this.
> > with bwrap https://gist.github.com/guymanley/512e29b4ca5606e9475e42246ddfd7a5
> > no bwrap https://gist.github.com/guymanley/52188922b0ee3b0e8430b5fbc189f8ba
> > I was able to enter a game's menu, click around with its file explorer, presumably everything else should work too.
> 
> Thanks for the logs! It looks like the bwrap launcher is getting stuck for some reason. Can you or anyone else in this thread try running the following command and see what output it produces:
> 
> ```
> flatpak run com.github.Matoking.protontricks -v -c "bash -x wine --version" APPID
> ```
> 
> Replace the `APPID` with the app ID for the game that's causing issues. It's the number at the end of each title when Protontricks asks you to choose a game from a list (eg. 753640 in "Outer Wilds: 753640" is the app ID).
> 
> I'm guessing the command will get stuck somehow and either produce endless amounts of log lines, or just hang entirely. Knowing where it does so should hopefully nail down the issue.

Here's my test logs. Test version used https://gist.github.com/guymanley/b9145ae8b5f3d6c038b355f5ebe4a081

**Comment by guymanley** [comment]
Matoking posted the konsole command to install the test race condition fix version: here https://github.com/Matoking/protontricks/issues/164#issuecomment-1230564235

> Sorry to ask, but how can i install the test version on the steam deck?

**Comment by Matoking** [comment]
@guymanley Thank you! The issue seems to be that Protontricks on Flatpak didn't have access to a required service on the D-Bus. The only reason it worked on my system is because I had manually enabled session D-Bus access while testing something else and forgot about it. :facepalm: 

---

I've pushed a fix to Flathub which adds the missing permission and should fix commands hanging on bwrap; the update should be live in a few hours. It does _not_ have the random crash fix yet, though.

I've pushed a new test version which has both the missing permission and the earlier fix to the random crash bug. You can install it by running the following command:

```
flatpak install --user https://dl.flathub.org/build-repo/104927/com.github.Matoking.protontricks.flatpakref
```

**Please test and report whether this solves the remaining issues!** If so, I'll look into releasing a new version soon. The random crash bug might have been responsible for a bunch of hard-to-diagnose issues, so it would be nice to squash it for good. :)

**Comment by otuva** [comment]
- Official flatpak latest version (1.9.1)
- Both outputs: https://gist.github.com/otuva/2cf8790c5e708dc0a724dfb00915589b

- Test branch version
- Output: https://gist.github.com/otuva/d489487c7275eec95b5295b1d8d14d70

I can post system info too if you want

**Comment by guymanley** [comment]
Had to uninstall to get the new test version installed. Here's a test with bwrap, froze up again. https://gist.github.com/guymanley/3d3a33701f59b7b565b4fa3bf822cb63

And one with the --no-bwrap flag,  which works. https://gist.github.com/guymanley/42e687fd6a81b06417ac8b1d20392bb0

> @guymanley Thank you! The issue seems to be that Protontricks on Flatpak didn't have access to a required service on the D-Bus. The only reason it worked on my system is because I had manually enabled session D-Bus access while testing something else and forgot about it. facepalm
> 
> I've pushed a fix to Flathub which adds the missing permission and should fix commands hanging on bwrap; the update should be live in a few hours. It does _not_ have the random crash fix yet, though.
> 
> I've pushed a new test version which has both the missing permission and the earlier fix to the random crash bug. You can install it by running the following command:
> 
> ```
> flatpak install --user https://dl.flathub.org/build-repo/104927/com.github.Matoking.protontricks.flatpakref
> ```
> 
> **Please test and report whether this solves the remaining issues!** If so, I'll look into releasing a new version soon. The random crash bug might have been responsible for a bunch of hard-to-diagnose issues, so it would be nice to squash it for good. :)

**Comment by nabel0** [comment]
> @guymanley Thank you! The issue seems to be that Protontricks on Flatpak didn't have access to a required service on the D-Bus. The only reason it worked on my system is because I had manually enabled session D-Bus access while testing something else and forgot about it. 🤦
> 
> I've pushed a fix to Flathub which adds the missing permission and should fix commands hanging on bwrap; the update should be live in a few hours. It does _not_ have the random crash fix yet, though.
> 
> I've pushed a new test version which has both the missing permission and the earlier fix to the random crash bug. You can install it by running the following command:
> 
> ```
> flatpak install --user https://dl.flathub.org/build-repo/104927/com.github.Matoking.protontricks.flatpakref
> ```
> 
> **Please test and report whether this solves the remaining issues!** If so, I'll look into releasing a new version soon. The random crash bug might have been responsible for a bunch of hard-to-diagnose issues, so it would be nice to squash it for good. :)

Hi @Matoking ...It seems like you forgot to set the correct flatpak permissions in the new test version you posted above.
It still hangs for me. But after i gave it the propper permissions via Flatseal it works fine:

![Screenshot 2022-08-31 214235](https://user-images.githubusercontent.com/50377455/187768466-35ad3d1c-a56f-4013-a933-62db7a3b7a60.jpg)

@guymanley @otuva Can you try to set this permission via Flatseal and report back if it woks now for you (using the latest testversion posted above).

**Comment by Matoking** [comment]
> 
> Hi @Matoking ...It seems like you forgot to set the correct flatpak permissions in the new test version you posted above. It still hangs for me. But after i gave it the propper permissions via Flatseal it works fine:
> 
> screenshot
> 
> @guymanley @otuva Can you try to set this permission via Flatseal and report back if it woks now for you (using the latest testversion posted above).

Yep, noticed as much. Flatpak keeps old permissions around even after installing new versions that drop them.

The aim is not to enable entire access to the entire session bus, as that goes against the idea of sandboxing. I'll look into this again tomorrow; Protontricks does appear to have enough permissions to launch the process, it's closing down where things get hairy and the whole thing hangs. You can use the "D-Bus session bus" permission as a workaround for now.

**Comment by otuva** [comment]
> > @guymanley Thank you! The issue seems to be that Protontricks on Flatpak didn't have access to a required service on the D-Bus. The only reason it worked on my system is because I had manually enabled session D-Bus access while testing something else and forgot about it. facepalm
> > I've pushed a fix to Flathub which adds the missing permission and should fix commands hanging on bwrap; the update should be live in a few hours. It does _not_ have the random crash fix yet, though.
> > I've pushed a new test version which has both the missing permission and the earlier fix to the random crash bug. You can install it by running the following command:
> > ```
> > flatpak install --user https://dl.flathub.org/build-repo/104927/com.github.Matoking.protontricks.flatpakref
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **Please test and report whether this solves the remaining issues!** If so, I'll look into releasing a new version soon. The random crash bug might have been responsible for a bunch of hard-to-diagnose issues, so it would be nice to squash it for good. :)
> 
> Hi @Matoking ...It seems like you forgot to set the correct flatpak permissions in the new test version you posted above. It still hangs for me. But after i gave it the propper permissions via Flatseal it works fine:
> 
> ![Screenshot 2022-08-31 214235](https://user-images.githubusercontent.com/50377455/187768466-35ad3d1c-a56f-4013-a933-62db7a3b7a60.jpg)
> 
> @guymanley @otuva Can you try to set this permission via Flatseal and report back if it woks now for you (using the latest testversion posted above).

Yeah nice catch that's the reason it hangs with bubblewrap I guess. 

Strangest thing is even though gui works now I still cannot run any external executable with appid  from both CLI and GUI. The external exe won't even see the game's process. Tried running the exe with steamtinkerlaunch and it was able to see it. 

```
flatpak run com.github.Matoking.protontricks -c 'WINEFSYNC=1 wine /home/tfp/Downloads/CheatEngine74/cheatengine-x86_64.exe' 1454400
# or
protontricks-launch --no-bwrap --appid 1454400 /home/tfp/.var/app/com.valvesoftware.Steam/Desktop/CheatEngine74/cheatengine-x86_64.exe
```

STL broke some other things for reasons I can't even begin the find so.. still debugging lol

**Comment by Matoking** [comment]
I've reverted the D-Bus change on the Flatpak version of Protontricks for the time being, as I seem to be having trouble getting it working it with Flatpak. This update should be live in a few hours and get bwrap working again (and for real this time), though it's not a permanent solution due to `--socket` being deprecated.

As for the problem with D-Bus, the `Launch` event is emitted as normal, but `ProcessExited` signal is not emitted unless full session bus access is granted for some reason, even when Protontricks is granted access to different D-Bus services.

**Comment by guymanley** [comment]
Ok, I downloaded the test version again via "flatpak install --user https://dl.flathub.org/build-repo/104927/com.github.Matoking.protontricks.flatpakref" Seems the flathub version couldn't be found/downloaded by KDE Discover Added the d-Buss Session bus permission via Flatseal. I was about to launch via gui, get all the way to in Resident Evil HD but when I select run winecfg it just brings up the same window again.

 Konsole output replicating the issue here: https://gist.github.com/guymanley/ee98fbcd106c526c1d92a23aa6a1fdb1

This was not done with the --no-bwrap flag.

**Comment by landonepps** [comment]
This one worked for me: https://github.com/flathub/com.github.Matoking.protontricks/pull/31#issuecomment-1234733878
```
flatpak install --user https://dl.flathub.org/build-repo/105185/com.github.Matoking.protontricks.flatpakref
```

**Comment by guymanley** [comment]
> This one worked for me on SteamOS: [flathub/com.github.Matoking.protontricks#31 (comment)](https://github.com/flathub/com.github.Matoking.protontricks/pull/31#issuecomment-1234733878)
> 
> ```
> flatpak install --user https://dl.flathub.org/build-repo/105185/com.github.Matoking.protontricks.flatpakref
> ```

Tried this. While the gui works. Wine functions like winecfg, registry etc just come back to the same menu.

**Comment by Matoking** [comment]
The mentioned test build only had the patch for the D-Bus issue to keep it in line with the version 1.9.1. I made a new test build that has both fixes:

```
flatpak install --user https://dl.flathub.org/build-repo/105592/com.github.Matoking.protontricks.flatpakref
```

Please check if this solves the issue. Assuming it does, I'll try to push a new version out ASAP.

**Comment by guymanley** [comment]
So winecfg and the gui worked. Regedit, explorer, taskmanager just return to the previous menu. Maybe my issue is the test build didn't completely download? 2mb of 16. All in the Gist: https://gist.github.com/guymanley/8abbcffcd87f408d2c516d89f9b71187
I used the discover app to remove protontricks before replacing test builds.

**Comment by Matoking** [comment]
> So winecfg and the gui worked. Regedit, explorer, taskmanager just return to the previous menu. Maybe my issue is the test build didn't completely download? 2mb of 16. All in the Gist: https://gist.github.com/guymanley/8abbcffcd87f408d2c516d89f9b71187 I used the discover app to remove protontricks before replacing test builds.
> 
> I should clarify, the gist shows me installing the test build you posted lastly twice because I thought it failed the first time and uninstalled via discover, which is not shown in the gist. When the same behavior happened on the 2nd attempt to install, I just decided to move on with testing. I was able to edit a dll in Resident Evil 4 HD and remove the launch command override that did the same function so winecfg at least is working. Not sure how much else is not working.

I was able to reproduce the issue on Proton 7.0, but not Proton 6.3 using the following method:

```
# Open two terminal emulators.
# On the first one, open a Windows command prompt, and leave it open. This will ensure a wineserver process is left open.
$ protontricks -v --no-background-wineserver -c bash APPID
$ wine cmd.exe 

# On the second one, open Winetricks GUI as normal, then select winecfg, close it, and open winecfg again.
# It should crash with the same error.
$ protontricks -v --no-background-wineserver APPID --gui
```

My guess is it's related to the recent Steam Runtime update since `--no-bwrap` also fixes the issue, but I'll have to look into this more. Protontricks 1.9.0 and non-Flatpak environment also trigger the same error.

**Comment by Matoking** [comment]
I'm closing this issue since the Flatpak specific issue has been fixed. The another issue seemingly related to Steam Runtime is continued in #166.
